name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set GO environment variables
      run: |
        echo ::set-env name=GOPATH::$RUNNER_WORKSPACE/go 
        echo ::set-env name=GOBIN::$RUNNER_WORKSPACE/go/bin
    - name: Setup GO
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.1'
    - name: Move project to GO workspace
      run: |
        GOPROJECT=$GOPATH/src/github.com/$GITHUB_REPOSITORY
        echo "Moving $GITHUB_WORKSPACE to $GOPROJECT"
        mkdir -p $GOPROJECT
        cp -R $GITHUB_WORKSPACE $GOPROJECT
        echo ::set-env name=GOPROJECT::$GOPROJECT
    - name: Bootstrap & build
      run: |
        cd $GOPROJECT
        make bootstrap build