name: CI

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set Git Version
      uses: docker://gittools/gitversion:latest-linux-netcoreapp2.1
      with:
        args: /github/workspace /nofetch /exec /bin/sh /execargs "-c echo ::set-env name=GitVersion_FullSemVer::$GitVersion_FullSemVer"
    - name: Set GO environment variables
      run: |
        GOPATH=$RUNNER_WORKSPACE/go
        GOBIN=$GOPATH/bin
        mkdir -p $GOBIN
        echo ::set-env name=GOPATH::$GOPATH 
        echo ::set-env name=GOBIN::$GOBIN
        echo ::add-path::$GOBIN
    - name: Setup GO
      uses: actions/setup-go@v1
      with:
        go-version: '1.13.1'
    - name: Move project to GO workspace
      run: |
        GOPROJECT=$GOPATH/src/github.com/$GITHUB_REPOSITORY
        echo "Moving $GITHUB_WORKSPACE to $GOPROJECT"
        mkdir -p $GOPROJECT
        cp -a $GITHUB_WORKSPACE/. $GOPROJECT
        echo ::set-env name=GOPROJECT::$GOPROJECT
    - name: Bootstrap & build
      run: |
        cd $GOPROJECT   
        make bootstrap build-release
    - name: Upload build artifacts
      uses: actions/upload-artifact@master
      with:
        name: binaries
        path: ${{ runner.workspace }}/go/src/github.com/${{ github.repository}}/bin